version: "3.3"

services:
    db:
        image: hypriot/rpi-mysql
        restart: always
        volumes:
            - ./docker/mysql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: ${DBROOT}
            MYSQL_DATABASE: ${DBNAME}
            MYSQL_USER: ${DBUSER}
            MYSQL_PASSWORD: ${DBPASSWORD}

    webserver:
        image: nginx
        volumes:
            - ./config/statistics/:/announcer/statistics
            - ./resources/:/resources
            - ./logs/:/var/www/logs
            - ./web:/code
            - ./docker/nginx/:/etc/nginx/conf.d/
        ports:
            - 80:8050
        links:
            - php
    

    php:
        depends_on:
            - db
        build: ./docker/php
        volumes:
            - ./resources/:/announcer/resources
            - ./config/statistics/:/announcer/statistics
            - ./logs/:/var/www/logs
            - ./web:/code
        environment:
            - LOGIN=${WEBUSER}
            - PASSWORD=${WEBPASSWORD}
            - DBUSER=${DBUSER}
            - DBPASSWORD=${DBPASSWORD}
            - DBNAME=${DBNAME}
            - BRANCH=${BRANCH}

    adminer:
        depends_on:
            - db
        image: adminer
        restart: always
        ports:
            - '8080:8081'
        environment:
            ADMINER_DEFAULT_SERVER: db
            ADMINER_DESIGN: galkaev

    node:
        build: .
        depends_on: 
            - db
        restart: always
        ports:
            - '3000:3000'
        volumes:
            - ./resources/:/announcer/resources
            - ./config/statistics/:/announcer/statistics
            - ./logs/:/announcer/logs
        environment:
            - DBUSER=${DBUSER}
            - DBPASSWORD=${DBPASSWORD}
            - BOTKEY=${BOTKEY}
            - DBNAME=${DBNAME}
